#%RAML 1.0 Library

usage: Common traits for the Customer API

traits:
  pageable: !include pageable.raml
  orderble: !include orderble.raml
  versioned: !include versioned.raml
  partial: !include partial.raml
